Fedroio/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.views.static import serve

from . import views

urlpatterns = [
    path('', views.index),
    path('home/', views.home, name='home'),
    path('info/', views.info, name='info'),
    path('admin/', admin.site.urls),
    path('pawns/', include('pawns.urls')),
    path('interpares/', include('interpares.urls')),
    path('explore/', include('explore.urls')),
    path('achievments/', include('achievements.urls')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('', include('core.urls'))
] 

core/urls.py
from django.urls import path, include, re_path

from . import views

urlpatterns = [
    path('account', views.account, name='account'),
    path('account/settings', views.settings, name='settings'),
    path('utente/sapphires', views.user_sappire, name='user.sapphires'),
    path('utente/<str:username>', views.user, name='user'),
    path('utente/<str:username>/delete', views.user_delete, name='user.delete'),
    path('utente/<str:username>/reset', views.user_reset, name='user.reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/sign-up', views.signup, name='signup'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit-group/<int:id>', views.group_edit, name='core.group.edit'),
    path('new-group', views.group_new, name='core.group.new'),
    path('group/<int:id>/partis', views.group_partis, name='core.group.partis'),
    path('group/<int:id>/partis/<int:pawn_id>/stats', views.group_partis_reset, name='group_partis_reset'),
    path('group/<int:id>/partis/<int:pawn_id>', views.group_partis_stats, name='group_partis_stats'),
    path('delete-group/<int:id>', views.group_delete, name='core.group.delete'),
]

core/models.py
import random, string
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db import models
from django.contrib.auth.hashers import make_password

class User(AbstractUser):
    bio = models.TextField(null=True, blank=True)
    THEME_CHOICES = [
        ('red', 'Red'),
        ('blue', 'Blue'),
        ('green', 'Green'),
        ('yellow', 'Yellow'),
    ]
    theme = models.CharField(max_length=6, choices=THEME_CHOICES, default='blue')
    sapphires = models.PositiveBigIntegerField(default=0)

    def url(self):
        return reverse('user', kwargs={'username': self.username})

    def url_delete(self):
        return reverse('user.delete', kwargs={'username': self.username})

    def url_reset(self):
        return reverse('user.reset', kwargs={'username': self.username})

    def pawns(self):
        from pawns.models import Pawn
        return Pawn.objects.filter(user=self, parent=None)

    def reset_password(self):
        new_password = ''.join(random.choices(string.ascii_letters + string.digits, k=8))
        self.set_password(new_password) 
        self.save()
        return new_password

    def answer(self, question, state):
        from pawns.models import QuestionSubmitted
        a, _ = QuestionSubmitted.objects.get_or_create(question=question, user=self)
        if state:
            a.correctly += 1   
        else:
            a.wrongly += 1
        a.save()

templates/_back.html
<button class="w3-btn w3-round w3-theme w3-card" onclick="window.history.back();">
    <i class="fa fa-arrow-left"></i>
</button>

templates/_panel.html
<div class="w3-col m{{ col|default:'12' }} w3-padding-small">
    <div class="w3-panel w3-white w3-card w3-round w3-border w3-border-theme w3-row" style="{{ style }}">
        {% block content %}{% endblock %}
    </div>
</div>

templates/ask.html
{% extends "layout/base.html" %}

{% block title %}Ask{% endblock %}

{% block content %}

    <div class="w3-panel w3-white w3-card-4 w3-round">
        <h1>{{ title }}</h1>
    </div>

    <div class="w3-panel w3-white w3-card-4 w3-round">
        <form method="post">
            <div class="w3-panel w3-white w3-card-4 w3-round">
                <form method="post">
                    {% csrf_token %}
                    <div class="w3-panel">
                        {{ text|safe }}
                    </div>
                    <div class="w3-center w3-panel">
                        <div class="w3-large">
                            Are you sure?
                        </div>
                        <a href="{{ url_back }}" class="w3-btn">
                            <i class="fa fa-arrow-left"></i>
                            Back
                        </a>
                        <button type="submit" class="w3-btn w3-theme w3-round w3-card">
                            Accept
                            <i class="fa fa-check"></i>
                        </button>
                    </div>
                </form>
            </div>
        </form>
    </div>
{% endblock %}

templates/dashboard.html
{% extends "layout/base.html" %}

{% block title %}Admin{% endblock %}

{% block content %}

<div class="w3-panel w3-card-4 w3-round w3-white">
    <h1>Utenti</h1>
    <div class="w3-panel">
        {% url 'signup' as url %}
        {% include 'partials/abutton-admin.html' with url=url title='Nuovo utente' icon='user-plus' class='w3-right'%}
    </div>
    <table class="w3-table-all w3-card w3-margin-bottom">
        {% for user in users %}
            <tr>
                <td>{{ user }}</td>
                <td>
                    {% include 'partials/abutton-admin.html' with url=user.url title='Profilo' icon='user'%}
                    {% include 'partials/abutton-admin.html' with url=user.url_reset title='Reset password' icon='key'%}
                    {% include 'partials/abutton-admin.html' with url=user.url_delete title='Elimina account' icon='trash'%}
                    <form action="{% url 'user.sapphires' %}"  class="w3-right" method="post" style="display: inline;">
                        <input type="hidden" name="user" value="{{ user.id }}">
                        {% csrf_token %}
                        <input value="{{ user.sapphires }}" class="w3-input w3-card w3-round w3-quarter" type="number" name="sapphires">
                        <button class="w3-btn w3-round w3-card-4" type="submit">Salva <i class="fa fa-save"></i></button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
</div>

<div class="w3-panel w3-card-4 w3-round w3-white">
    <h1>Gruppi</h1>
    <div class="w3-panel">
        {% url 'core.group.new' as url %}
        {% include 'partials/abutton-admin.html' with url=url title='Nuovo gruppo' icon='plus' class='w3-right'%}
    </div>
    <table class="w3-table-all w3-card w3-margin-bottom w3-margin-top">
        {% for group in groups %}
        <tr>
            <td>{{ group }}</td>
            <td>{{ group.user_set.all|join:', ' }}</td>
            <td>
                <a href="{% url 'core.group.edit' id=group.id %}" class="w3-btn w3-round w3-card w3-theme">
                    Modifica <i class="fa fa-edit"></i>
                </a>
                <a href="{% url 'core.group.partis' id=group.id %}" class="w3-btn w3-round w3-card w3-black">
                    Partis <i class="fa fa-film"></i>
                </a>
                <a href="{% url 'core.group.delete' id=group.id %}" class="w3-btn w3-round w3-card w3-red">
                    Elimina <i class="fa fa-trash"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

<div class="w3-panel w3-card-4 w3-round w3-white">
    <h1>Domande errore</h1>
    <table class="w3-table-all w3-card w3-margin-bottom">
        {% for question in questions %}
            {% if question.error %}
                <tr>
                    <td>{{ question }}</td>
                    <td>
                        {% include 'partials/abutton-admin.html' with url=question.url_edit title='Edit question' icon='edit'%}
                        {% include 'partials/abutton-admin.html' with url=question.url_delete title='Delete question' icon='trash'%}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
</div>

{% endblock %}

templates/index.html
{% extends "layout/base.html" %}

{% block title %}Fedroio{% endblock %}

{% block content %}
    <div class="" style="max-width: 1000px; margin: auto;">

    <div class="w3-panel w3-white w3-card-4 w3-round">
        {% load static %}   
        <img class="w3-left w3-margin" style="width: 5em" src="{% static "img/loco.png" %}" alt="logo Fedro">
        <img class="w3-right w3-margin w3-hide-small" style="width: 5em" src="{% static "img/loco.png" %}" alt="logo Fedro">
        <h1 class="w3-center">Fedro.io</h1>
        <h3 class="w3-center w3-text-grey w3-small">
            "Apprendimento efficace, potenziato dal gioco." <sub>cit. GPT 4o</sub>
        </h3>
    </div>

    <div class="w3-panel w3-row">
        {% for pawn in pawns %}
        <div class="w3-col m6  w3-padding">
            <div class="w3-panel w3-white w3-card w3-round">
                <h3 class="w3-center">{{ pawn }}</h3>
                <p class="w3-margin">
                    {{ pawn.text|safe|truncatechars:128 }}
                </p>
                {% if pawn.image %}
                <div class="w3-container w3-padding w3-center">
                    <img src="{{ pawn.image.url }}" style="max-height: 100px;" class="w3-round">
                </div>
                {% endif %}
                <div class="w3-panel w3-right">
                    <a href="{{ pawn.url }}" class="w3-btn w3-theme w3-card w3-round">
                        Raggiungi il Pawn
                        <i class="fa fa-arrow-right"></i>
                    </a>
                </div>
            </div>
        </div>
            {% endfor %}
        
    </div>

    <div class="w3-white w3-card-4 w3-round w3-row">
        <div class="w3-third w3-round w3-panel w3-center">
            <a href="{% url 'pawns' %}" class="w3-btn w3-border-theme w3-border w3-card w3-round"><h3>Pawns <i class="fa fa-sitemap"></i> </h3></a>
            <p>Abbiamo creato un sistema gerarchico che organizza la conoscenza in singoli <strong>Pawn</strong> (pedoni), semplificando l'apprendimento e la gestione delle informazioni.</p>
        </div>
        <div class="w3-third w3-round w3-panel w3-center">
            <a href="{% url 'pawns' %}" class="w3-btn w3-border-theme w3-border w3-card w3-round"><h3>Quiz <i class="fa fa-question-circle"></i></h3></a>
            <p>I nostri <strong>Quiz</strong> legano ogni "pawn" a domande, semplificando l'apprendimento e il monitoraggio, con opzioni per competere o accedere anonimamente.</p>
        </div>
        <div class="w3-third w3-round w3-panel w3-center">
            <a href="{% url 'interpares' %}" class="w3-btn w3-border-theme w3-border w3-card w3-round"><h3>Community <i class="fa fa-film"></i></h3></a>
            <p>Metodologia di correzione <strong>Interpares</strong> abilitabile dagli amminisratori</p>
        </div>
    </div>
        <div class="w3-card-4 w3-round w3-theme">
            <p class="w3-center">
                &copy; 2024 Fedro.io
            </p>
        </div>
    </div>
</div>
   
{% endblock %}

templates/info.html
{% extends "layout/base.html" %}

{% block title %}Index{% endblock %}

{% block content %}

    <div class="w3-panel w3-white w3-card-4 w3-round">
        <h1>Fedroio</h1>
    </div>
    <div class="w3-panel w3-white w3-card-4 w3-round">
        <h3>Questions</h3>
        <p>Attualmente nel sito sono memorizzate <b>{{ questions.count }}</b> domanda a risposta chiusa e <b>{{ sentences.count }}</b> frasi primitive per creare i coze-test</p>
    </div>
   
    <div class="w3-panel w3-white w3-card-4 w3-round">
        <h3>Pawns</h3>
        <p>
            Nel nostro sistema, abbiamo sviluppato una struttura dati gerarchica innovativa, progettata per schematizzare e organizzare la conoscenza
            proveniente da diversi ambiti in un unico sistema generalizzato. Alla base di questa struttura vi è il concetto di <strong>pawn</strong> (pedone), che rappresenta
            l'unità primitiva e fondamentale del nostro modello.
        </p>
        <p class="w3-card w3-round w3-border w3-border-theme w3-margin w3-padding">
            Ad esempio, l'ICDL è un "pawn", suddiviso a sua volta in moduli, ciascuno dei quali rappresenta anch'esso un "pawn". Ogni modulo è ulteriormente articolato
            in capitoli, che costituiscono ulteriori "pawns", e così via fino ai paragrafi.
        </p>
        <p>
            Grazie a questa logica gerarchica, siamo in grado di schematizzare corsi universitari, libri, seminari, progetti e molte altre forme di conoscenza in modo strutturato
            e coerente. Questo approccio ci consente di offrire una mappatura precisa e organizzata delle informazioni, facilitando l'apprendimento e la gestione dei contenuti.
        </p>
    </div>
      
    <div class="w3-panel w3-white w3-card-4 w3-round">
        <h3 id="sapphires">Sapphires</h3>
        <p>
            Il sistema utilizza una valuta virtuale denominata <strong>Sapphires</strong> per premiare gli utenti in base ai loro risultati. Ogni utente può guadagnare
            Sapphires completando quiz, risolvendo esami e accumulando punti. Questo sistema incentiva l'apprendimento e la partecipazione, creando una dinamica
            divertente e motivante.
        </p>
        <p>
            I Sapphires non sono solo un riconoscimento simbolico: raggiunta una determinata soglia, gli utenti possono utilizzarli per creare nuovi <strong>pawns</strong>.
            Questo consente loro di contribuire direttamente alla crescita del sistema, arricchendolo con conoscenze, argomenti o contenuti strutturati di loro
            iniziativa. 
        </p>
        <p>
            Questo approccio offre un incentivo continuo all'apprendimento, premiando la dedizione e incoraggiando la collaborazione tra gli utenti. Ogni nuovo 
            pawn creato è un tassello in più nel nostro ecosistema di conoscenza, rendendo il sistema sempre più completo e coinvolgente.
        </p>
        <p class="w3-card w3-round w3-border w3-border-theme w3-margin w3-padding">
            <em>Esempio:</em> Completando un quiz con un punteggio elevato, un utente guadagna 50 Sapphires. Dopo aver accumulato 500 Sapphires, può creare un nuovo 
            pawn personalizzato, aggiungendo al sistema una nuova area tematica o un approfondimento specifico.
        </p>
    </div>

    <div class="w3-panel w3-white w3-card-4 w3-round">
        <h3>Quiz</h3>
        <p>
            L'integrazione dei <strong>Quiz</strong> nel nostro sistema ha reso possibile associare a ciascun "pawn" una serie di domande a risposta multipla, facilitando l'apprendimento e
            la memorizzazione dei contenuti. Questa funzionalità, ispirata dalle simulazioni degli esami ICDL, consente non solo di consolidare le conoscenze acquisite,
            ma anche di monitorare i progressi attraverso punteggi e classifiche (in fase di sviluppo).
        </p>
        <p>
            Gli utenti autenticati possono visualizzare le classifiche e confrontare i propri risultati con quelli degli altri, creando un ambiente di apprendimento
            competitivo e stimolante. Tuttavia, offriamo anche la possibilità di accedere ai quiz in forma anonima, per permettere a chiunque di mettere alla prova le
            proprie conoscenze in modo semplice e immediato.
        </p>
    </div>

    <div class="w3-panel w3-white w3-card-4 w3-round">
        <h3 id="coze">Coze Test</h3>
        <p>
            Abbiamo recentemente introdotto i Coze Test, una funzionalità che permette di associare a ogni "pawn" delle frasi significative. Il sistema poi presenta
            queste frasi agli utenti, nascondendo le parole principali e richiedendo che l'utente le completi correttamente. Questo approccio non solo aiuta a consolidare
            la comprensione del contenuto, ma offre anche un modo interattivo e coinvolgente per rinforzare la memoria e verificare la padronanza dei concetti chiave.
        </p>
        <p>
            
        </p>
    </div>
{% endblock %}